### ISSUE TITLE
undefined method `prepend' under Ruby 1.9.3

### ISSUE THREAD

**Issue by MosZhao** [Restream/redmine_user_specific_theme#9]
Hi!

This plugin can't work with Ruby 1.9.3 anymore?
